[tool.poetry]
name = "gw2"
version = "0.0.1"
description = ""
repository = "https://github.com/invisi/python-gw2"
authors = ["Yannick Linke <invisi@0x0f.net>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
httpx = "^0.18.2"
pydantic = "^1.8.2"
python = "^3.8"

[tool.poetry.dev-dependencies]
respx = "^0.17.0"
mypy = "^0.910"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
