[tool.poetry]
name = "gw2"
version = "0.1.0"
description = ""
repository = "https://github.com/invisi/python-gw2"
authors = ["Yannick Linke <invisi@0x0f.net>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
httpx = "^0.23.1"
pydantic = "^1.10.3"
python = "^3.10"
mypy = "^0.991"

[tool.poetry.dev-dependencies]
respx = "^0.20.1"
mypy = "0.*"

[tool.ruff]
line-length = 88
fix = true
ignore-init-module-imports = true
select = ["E", "F", "I", "UP", "N", "B", "T20", "Q", "PLC", "PLE", "PLR", "PLW"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.black]
line-length = 88

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
