[tool.poetry]
name = "gw2"
version = "0.0.6"
description = ""
repository = "https://github.com/invisi/python-gw2"
authors = ["Yannick Linke <invisi@0x0f.net>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
httpx = "^0.21.1"
pydantic = "^1.9.0"
python = "^3.8"

[tool.poetry.dev-dependencies]
respx = "^0.19.0"
mypy = "^0.930"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
