[tool.poetry]
name = "gw2"
version = "0.0.9"
description = ""
repository = "https://github.com/invisi/python-gw2"
authors = ["Yannick Linke <invisi@0x0f.net>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
httpx = "^0.22.0"
pydantic = "^1.9.0"
python = "^3.8"

[tool.poetry.dev-dependencies]
respx = "^0.19.2"
mypy = "0.*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
